spring:
  application:
    name: zipkin
  zipkin:
    service:
      name: zipkin
    baseUrl: http://localhost:9411


server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8490/eureka/"

zipkin:
  store:
    type: mem
  query:
    allowed-origins: "*"

logging:
  level:
    com.netflix.discovery: 'OFF'