server:
  port: 8460

spring:
  application:
    name: baking
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411
    service:
      name: baking

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8490/eureka/"
    eureka-service-url-poll-interval-seconds: 10

logging:
  level:
    com.netflix.discovery: 'OFF'
