server:
  port: 8460

spring:
  application:
    name: baking
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:8499
    service:
      name: baking

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8490/eureka/"

logging:
  level:
    com.netflix.discovery: 'OFF'
