server:
  port: 8410

spring:
  jackson:
    mapper:
      INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: true
  application:
    name: storage
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
    service:
      name: 'storage'

logging:
  level:
    com.netflix.discovery: 'OFF'

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8490/eureka/"

